#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-iot-sdk
Version  : elease.2018.10.31
Release  : 26
URL      : https://github.com/Azure/azure-iot-sdk-python/archive/release_2018_10_31.tar.gz
Source0  : https://github.com/Azure/azure-iot-sdk-python/archive/release_2018_10_31.tar.gz
Source1  : https://github.com/Azure/azure-c-shared-utility/archive/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
Source2  : https://github.com/Azure/azure-c-shared-utility/archive/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
Source3  : https://github.com/Azure/azure-c-shared-utility/archive/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
Source4  : https://github.com/Azure/azure-c-shared-utility/archive/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
Source5  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source6  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source7  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source8  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source9  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source10  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source11  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source12  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source13  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source14  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source15  : https://github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source16  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source17  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source18  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source19  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source20  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source21  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source22  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source23  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source24  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source25  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source26  : https://github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source27  : https://github.com/Azure/azure-iot-sdk-c/archive/abacd2311a1b6d9fabc0743acf494d418fac8a30.tar.gz
Source28  : https://github.com/Azure/azure-uamqp-c/archive/8da237b55317e575b361dd630ff5d862bc0b760c.tar.gz
Source29  : https://github.com/Azure/azure-uhttp-c/archive/d06524b543c52519e20da843d2df1d6e6e40a05d.tar.gz
Source30  : https://github.com/Azure/azure-umqtt-c/archive/640f9d649bd81f10ea6ce005e207cafe49ae3383.tar.gz
Source31  : https://github.com/Azure/azure-utpm-c/archive/a82e758bfcea806167e19d9dd94c2e1cc223aaee.tar.gz
Source32  : https://github.com/Azure/umock-c/archive/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
Source33  : https://github.com/Azure/umock-c/archive/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
Source34  : https://github.com/Azure/umock-c/archive/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
Source35  : https://github.com/Azure/umock-c/archive/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
Source36  : https://github.com/Azure/umock-c/archive/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
Source37  : https://github.com/Microsoft/RIoT/archive/bc97a5eaff53535eddbdf95b4f477c6caf3b7788.tar.gz
Source38  : https://github.com/kgabis/parson/archive/0a1896939faff5f69e179637fc49f678ff0128ba.tar.gz
Source39  : https://www.github.com/Azure/azure-c-shared-utility/archive/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
Source40  : https://www.github.com/Azure/azure-c-testrunnerswitcher/archive/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
Source41  : https://www.github.com/Azure/azure-ctest/archive/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
Source42  : https://www.github.com/Azure/umock-c/archive/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: azure-iot-sdk-lib = %{version}-%{release}
Requires: azure-iot-sdk-license = %{version}-%{release}
Requires: azure-iot-sdk-python = %{version}-%{release}
Requires: azure-iot-sdk-python3 = %{version}-%{release}
Requires: msrest
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : curl-dev
BuildRequires : msrest
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libcurl)
BuildRequires : python3-dev
BuildRequires : util-linux-dev
Patch1: 0001-Use-Python-3.8.patch
Patch2: 0002-Don-t-link-iothub_client-lib-to-itself.patch
Patch3: 0003-Remove-_dll-from-library-name.patch
Patch4: 0004-Link-to-proper-shared-object.patch

%description
DICE/RIoT Test and Tools

%package dev
Summary: dev components for the azure-iot-sdk package.
Group: Development
Requires: azure-iot-sdk-lib = %{version}-%{release}
Provides: azure-iot-sdk-devel = %{version}-%{release}
Requires: azure-iot-sdk = %{version}-%{release}

%description dev
dev components for the azure-iot-sdk package.


%package lib
Summary: lib components for the azure-iot-sdk package.
Group: Libraries
Requires: azure-iot-sdk-license = %{version}-%{release}

%description lib
lib components for the azure-iot-sdk package.


%package license
Summary: license components for the azure-iot-sdk package.
Group: Default

%description license
license components for the azure-iot-sdk package.


%package python
Summary: python components for the azure-iot-sdk package.
Group: Default
Requires: azure-iot-sdk-python3 = %{version}-%{release}

%description python
python components for the azure-iot-sdk package.


%package python3
Summary: python3 components for the azure-iot-sdk package.
Group: Default
Requires: python3-core

%description python3
python3 components for the azure-iot-sdk package.


%prep
%setup -q -n azure-iot-sdk-python-release_2018_10_31
cd %{_builddir}
tar xf %{_sourcedir}/abacd2311a1b6d9fabc0743acf494d418fac8a30.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/0a1896939faff5f69e179637fc49f678ff0128ba.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/d06524b543c52519e20da843d2df1d6e6e40a05d.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/bc97a5eaff53535eddbdf95b4f477c6caf3b7788.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/a82e758bfcea806167e19d9dd94c2e1cc223aaee.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/8da237b55317e575b361dd630ff5d862bc0b760c.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/640f9d649bd81f10ea6ce005e207cafe49ae3383.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/4deb950a4154e9baa39c87d75dd323dd58e239b7.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/c2c0f18d785ba85fef213302266f520c64201bb1.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/b1d09aff8212f1fb62ca9d6014cb3509d8b5559a.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/721daafd8c34616f77a7697210470c0227dca20b.tar.gz
cd %{_builddir}/azure-iot-sdk-python-release_2018_10_31
mkdir -p c
cp -r %{_builddir}/azure-iot-sdk-c-abacd2311a1b6d9fabc0743acf494d418fac8a30/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c
mkdir -p c/c-utility
cp -r %{_builddir}/azure-c-shared-utility-4deb950a4154e9baa39c87d75dd323dd58e239b7/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility
mkdir -p c/c-utility/testtools/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/ctest
mkdir -p c/c-utility/testtools/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/testrunner
mkdir -p c/c-utility/testtools/umock-c
cp -r %{_builddir}/umock-c-c2c0f18d785ba85fef213302266f520c64201bb1/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/umock-c
mkdir -p c/c-utility/testtools/umock-c/deps/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/umock-c/deps/ctest
mkdir -p c/c-utility/testtools/umock-c/deps/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/umock-c/deps/testrunner
mkdir -p c/deps/parson
cp -r %{_builddir}/parson-0a1896939faff5f69e179637fc49f678ff0128ba/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/parson
mkdir -p c/deps/uhttp
cp -r %{_builddir}/azure-uhttp-c-d06524b543c52519e20da843d2df1d6e6e40a05d/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp
mkdir -p c/deps/uhttp/deps/c-utility
cp -r %{_builddir}/azure-c-shared-utility-4deb950a4154e9baa39c87d75dd323dd58e239b7/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility
mkdir -p c/deps/uhttp/deps/c-utility/testtools/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/ctest
mkdir -p c/deps/uhttp/deps/c-utility/testtools/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/testrunner
mkdir -p c/deps/uhttp/deps/c-utility/testtools/umock-c
cp -r %{_builddir}/umock-c-c2c0f18d785ba85fef213302266f520c64201bb1/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/umock-c
mkdir -p c/deps/uhttp/deps/c-utility/testtools/umock-c/deps/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/umock-c/deps/ctest
mkdir -p c/deps/uhttp/deps/c-utility/testtools/umock-c/deps/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/umock-c/deps/testrunner
mkdir -p c/provisioning_client/deps/RIoT
cp -r %{_builddir}/RIoT-bc97a5eaff53535eddbdf95b4f477c6caf3b7788/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/RIoT
mkdir -p c/provisioning_client/deps/utpm
cp -r %{_builddir}/azure-utpm-c-a82e758bfcea806167e19d9dd94c2e1cc223aaee/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm
mkdir -p c/provisioning_client/deps/utpm/deps/c-utility
cp -r %{_builddir}/azure-c-shared-utility-4deb950a4154e9baa39c87d75dd323dd58e239b7/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility
mkdir -p c/provisioning_client/deps/utpm/deps/c-utility/testtools/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/ctest
mkdir -p c/provisioning_client/deps/utpm/deps/c-utility/testtools/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/testrunner
mkdir -p c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c
cp -r %{_builddir}/umock-c-c2c0f18d785ba85fef213302266f520c64201bb1/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c
mkdir -p c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/ctest
mkdir -p c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/testrunner
mkdir -p c/uamqp
cp -r %{_builddir}/azure-uamqp-c-8da237b55317e575b361dd630ff5d862bc0b760c/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp
mkdir -p c/uamqp/deps/azure-c-shared-utility
cp -r %{_builddir}/azure-c-shared-utility-4deb950a4154e9baa39c87d75dd323dd58e239b7/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility
mkdir -p c/uamqp/deps/azure-c-shared-utility/testtools/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/ctest
mkdir -p c/uamqp/deps/azure-c-shared-utility/testtools/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/testrunner
mkdir -p c/uamqp/deps/azure-c-shared-utility/testtools/umock-c
cp -r %{_builddir}/umock-c-c2c0f18d785ba85fef213302266f520c64201bb1/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/umock-c
mkdir -p c/uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/ctest
mkdir -p c/uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/testrunner
mkdir -p c/uamqp/deps/azure-c-testrunnerswitcher
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-testrunnerswitcher
mkdir -p c/uamqp/deps/azure-ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-ctest
mkdir -p c/uamqp/deps/umock-c
cp -r %{_builddir}/umock-c-c2c0f18d785ba85fef213302266f520c64201bb1/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/umock-c
mkdir -p c/uamqp/deps/umock-c/deps/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/umock-c/deps/ctest
mkdir -p c/uamqp/deps/umock-c/deps/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/umock-c/deps/testrunner
mkdir -p c/umqtt
cp -r %{_builddir}/azure-umqtt-c-640f9d649bd81f10ea6ce005e207cafe49ae3383/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt
mkdir -p c/umqtt/deps/c-utility
cp -r %{_builddir}/azure-c-shared-utility-4deb950a4154e9baa39c87d75dd323dd58e239b7/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility
mkdir -p c/umqtt/deps/c-utility/testtools/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/ctest
mkdir -p c/umqtt/deps/c-utility/testtools/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/testrunner
mkdir -p c/umqtt/deps/c-utility/testtools/umock-c
cp -r %{_builddir}/umock-c-c2c0f18d785ba85fef213302266f520c64201bb1/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/umock-c
mkdir -p c/umqtt/deps/c-utility/testtools/umock-c/deps/ctest
cp -r %{_builddir}/azure-ctest-b1d09aff8212f1fb62ca9d6014cb3509d8b5559a/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/umock-c/deps/ctest
mkdir -p c/umqtt/deps/c-utility/testtools/umock-c/deps/testrunner
cp -r %{_builddir}/azure-c-testrunnerswitcher-721daafd8c34616f77a7697210470c0227dca20b/* %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/umock-c/deps/testrunner
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
## build_prepend content
# Disable -Werror everywhere
find . -type f -iname '*cmake*' -exec sed -i 's/-Werror//g' {} \;

# Point to the correct Boost Python libs
find . -type f -iname '*cmake*' -exec sed -i 's/python-py/python/g' {} \;
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581458518
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -Dskip_samples=ON \
-Duse_edge_modules=ON \
-Duse_prov_client=ON \
-Dbuild_as_dynamic=ON
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1581458518
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/azure-iot-sdk
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/6139d90e341cffe78b5b3f5a0f6c1becb6b6a4c7
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/b936129838be63462c2583bfd059d8736f39ab87
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/c-utility/testtools/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/parson/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/907314f1b5ac6f68c1906863389e4f2bed2a284d
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/03e1fe6fd0bc6d73c3cd3370d5f0a73c4fcb60d6
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/b936129838be63462c2583bfd059d8736f39ab87
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/deps/uhttp/deps/c-utility/testtools/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device/packaging/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/31034815375ad687af0a1b5d1c039587d3e93759
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/RIoT/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/03e1fe6fd0bc6d73c3cd3370d5f0a73c4fcb60d6
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/fc3defdb0ec07babc6fa8696113812c5a4ccd74a
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/b936129838be63462c2583bfd059d8736f39ab87
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/fcd11f2e53968b872b48efbb6cf2a18c5a0d04e5
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/b936129838be63462c2583bfd059d8736f39ab87
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/azure-ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/uamqp/deps/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/6298ab377445ac77e0146fe1794ff402f52b5631
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/azure-iot-sdk/b936129838be63462c2583bfd059d8736f39ab87
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/azure-iot-sdk-python-release_2018_10_31/c/umqtt/deps/c-utility/testtools/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
pushd clr-build
%make_install
popd
## install_append content
export LD_LIBRARY_PATH=%{buildroot}/usr/lib64

install -m 0755 clr-build/c/provisioning_client/deps/libmsr_riot.so %{buildroot}/usr/lib64/libmsr_riot.so
install -m 0755 clr-build/c/provisioning_client/deps/utpm/libutpm.so %{buildroot}/usr/lib64/libutpm.so

pushd ./build_all/linux/release_device_client
cp -t iothub_client ../../../clr-build/c/python/src/iothub_client.so
python3 setup.py install --root=%{buildroot}
popd

pushd ./build_all/linux/release_service_client
cp -t iothub_service_client ../../../clr-build/c/python_service_client/src/iothub_service_client.so
python3 setup.py install --root=%{buildroot}
popd

#pushd ./build_all/linux/release_provisioning_device_client
#cp ../../../clr-build/c/provisioning_device_client_python/src/provisioning_device_client.so provisioning_device_client/provisioning_device_client.so
#python setup.py install
#popd
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/azure_c_shared_utility/agenttime.h
/usr/include/azure_c_shared_utility/base32.h
/usr/include/azure_c_shared_utility/base64.h
/usr/include/azure_c_shared_utility/buffer_.h
/usr/include/azure_c_shared_utility/condition.h
/usr/include/azure_c_shared_utility/connection_string_parser.h
/usr/include/azure_c_shared_utility/consolelogger.h
/usr/include/azure_c_shared_utility/const_defines.h
/usr/include/azure_c_shared_utility/constbuffer.h
/usr/include/azure_c_shared_utility/constmap.h
/usr/include/azure_c_shared_utility/crt_abstractions.h
/usr/include/azure_c_shared_utility/doublylinkedlist.h
/usr/include/azure_c_shared_utility/envvariable.h
/usr/include/azure_c_shared_utility/gb_rand.h
/usr/include/azure_c_shared_utility/gb_stdio.h
/usr/include/azure_c_shared_utility/gb_time.h
/usr/include/azure_c_shared_utility/gballoc.h
/usr/include/azure_c_shared_utility/gbnetwork.h
/usr/include/azure_c_shared_utility/hmac.h
/usr/include/azure_c_shared_utility/hmacsha256.h
/usr/include/azure_c_shared_utility/http_proxy_io.h
/usr/include/azure_c_shared_utility/httpapi.h
/usr/include/azure_c_shared_utility/httpapiex.h
/usr/include/azure_c_shared_utility/httpapiexsas.h
/usr/include/azure_c_shared_utility/httpheaders.h
/usr/include/azure_c_shared_utility/linux_time.h
/usr/include/azure_c_shared_utility/lock.h
/usr/include/azure_c_shared_utility/macro_utils.h
/usr/include/azure_c_shared_utility/map.h
/usr/include/azure_c_shared_utility/optimize_size.h
/usr/include/azure_c_shared_utility/optionhandler.h
/usr/include/azure_c_shared_utility/platform.h
/usr/include/azure_c_shared_utility/refcount.h
/usr/include/azure_c_shared_utility/refcount_os.h
/usr/include/azure_c_shared_utility/sastoken.h
/usr/include/azure_c_shared_utility/sha-private.h
/usr/include/azure_c_shared_utility/sha.h
/usr/include/azure_c_shared_utility/shared_util_options.h
/usr/include/azure_c_shared_utility/singlylinkedlist.h
/usr/include/azure_c_shared_utility/socketio.h
/usr/include/azure_c_shared_utility/stdint_ce6.h
/usr/include/azure_c_shared_utility/string_token.h
/usr/include/azure_c_shared_utility/string_tokenizer.h
/usr/include/azure_c_shared_utility/string_tokenizer_types.h
/usr/include/azure_c_shared_utility/strings.h
/usr/include/azure_c_shared_utility/strings_types.h
/usr/include/azure_c_shared_utility/threadapi.h
/usr/include/azure_c_shared_utility/tickcounter.h
/usr/include/azure_c_shared_utility/tlsio.h
/usr/include/azure_c_shared_utility/tlsio_openssl.h
/usr/include/azure_c_shared_utility/tlsio_options.h
/usr/include/azure_c_shared_utility/umock_c_prod.h
/usr/include/azure_c_shared_utility/uniqueid.h
/usr/include/azure_c_shared_utility/urlencode.h
/usr/include/azure_c_shared_utility/utf8_checker.h
/usr/include/azure_c_shared_utility/uuid.h
/usr/include/azure_c_shared_utility/uws_client.h
/usr/include/azure_c_shared_utility/uws_frame_encoder.h
/usr/include/azure_c_shared_utility/vector.h
/usr/include/azure_c_shared_utility/vector_types.h
/usr/include/azure_c_shared_utility/vector_types_internal.h
/usr/include/azure_c_shared_utility/ws_url.h
/usr/include/azure_c_shared_utility/wsio.h
/usr/include/azure_c_shared_utility/x509_openssl.h
/usr/include/azure_c_shared_utility/xio.h
/usr/include/azure_c_shared_utility/xlogging.h
/usr/include/azure_prov_client/hsm_client_data.h
/usr/include/azure_prov_client/hsm_client_http_edge.h
/usr/include/azure_prov_client/hsm_client_riot.h
/usr/include/azure_prov_client/hsm_client_tpm.h
/usr/include/azure_prov_client/iothub_auth_client.h
/usr/include/azure_prov_client/iothub_security_factory.h
/usr/include/azure_prov_client/prov_auth_client.h
/usr/include/azure_prov_client/prov_client_const.h
/usr/include/azure_prov_client/prov_device_client.h
/usr/include/azure_prov_client/prov_device_ll_client.h
/usr/include/azure_prov_client/prov_sasl_tpm.h
/usr/include/azure_prov_client/prov_security_factory.h
/usr/include/azure_prov_client/prov_transport.h
/usr/include/azure_prov_client/prov_transport_amqp_client.h
/usr/include/azure_prov_client/prov_transport_amqp_common.h
/usr/include/azure_prov_client/prov_transport_amqp_ws_client.h
/usr/include/azure_prov_client/prov_transport_http_client.h
/usr/include/azure_prov_client/prov_transport_mqtt_client.h
/usr/include/azure_prov_client/prov_transport_mqtt_common.h
/usr/include/azure_prov_client/prov_transport_mqtt_ws_client.h
/usr/include/azure_prov_client/prov_transport_private.h
/usr/include/azure_uamqp_c/amqp_definitions.h
/usr/include/azure_uamqp_c/amqp_definitions_accepted.h
/usr/include/azure_uamqp_c/amqp_definitions_address_string.h
/usr/include/azure_uamqp_c/amqp_definitions_amqp_error.h
/usr/include/azure_uamqp_c/amqp_definitions_amqp_sequence.h
/usr/include/azure_uamqp_c/amqp_definitions_amqp_value.h
/usr/include/azure_uamqp_c/amqp_definitions_annotations.h
/usr/include/azure_uamqp_c/amqp_definitions_application_properties.h
/usr/include/azure_uamqp_c/amqp_definitions_attach.h
/usr/include/azure_uamqp_c/amqp_definitions_begin.h
/usr/include/azure_uamqp_c/amqp_definitions_close.h
/usr/include/azure_uamqp_c/amqp_definitions_connection_error.h
/usr/include/azure_uamqp_c/amqp_definitions_data.h
/usr/include/azure_uamqp_c/amqp_definitions_delivery_annotations.h
/usr/include/azure_uamqp_c/amqp_definitions_delivery_number.h
/usr/include/azure_uamqp_c/amqp_definitions_delivery_tag.h
/usr/include/azure_uamqp_c/amqp_definitions_detach.h
/usr/include/azure_uamqp_c/amqp_definitions_disposition.h
/usr/include/azure_uamqp_c/amqp_definitions_end.h
/usr/include/azure_uamqp_c/amqp_definitions_error.h
/usr/include/azure_uamqp_c/amqp_definitions_fields.h
/usr/include/azure_uamqp_c/amqp_definitions_filter_set.h
/usr/include/azure_uamqp_c/amqp_definitions_flow.h
/usr/include/azure_uamqp_c/amqp_definitions_footer.h
/usr/include/azure_uamqp_c/amqp_definitions_handle.h
/usr/include/azure_uamqp_c/amqp_definitions_header.h
/usr/include/azure_uamqp_c/amqp_definitions_ietf_language_tag.h
/usr/include/azure_uamqp_c/amqp_definitions_link_error.h
/usr/include/azure_uamqp_c/amqp_definitions_message_annotations.h
/usr/include/azure_uamqp_c/amqp_definitions_message_format.h
/usr/include/azure_uamqp_c/amqp_definitions_message_id_binary.h
/usr/include/azure_uamqp_c/amqp_definitions_message_id_string.h
/usr/include/azure_uamqp_c/amqp_definitions_message_id_ulong.h
/usr/include/azure_uamqp_c/amqp_definitions_message_id_uuid.h
/usr/include/azure_uamqp_c/amqp_definitions_milliseconds.h
/usr/include/azure_uamqp_c/amqp_definitions_modified.h
/usr/include/azure_uamqp_c/amqp_definitions_node_properties.h
/usr/include/azure_uamqp_c/amqp_definitions_open.h
/usr/include/azure_uamqp_c/amqp_definitions_properties.h
/usr/include/azure_uamqp_c/amqp_definitions_received.h
/usr/include/azure_uamqp_c/amqp_definitions_receiver_settle_mode.h
/usr/include/azure_uamqp_c/amqp_definitions_rejected.h
/usr/include/azure_uamqp_c/amqp_definitions_released.h
/usr/include/azure_uamqp_c/amqp_definitions_role.h
/usr/include/azure_uamqp_c/amqp_definitions_sasl_challenge.h
/usr/include/azure_uamqp_c/amqp_definitions_sasl_code.h
/usr/include/azure_uamqp_c/amqp_definitions_sasl_init.h
/usr/include/azure_uamqp_c/amqp_definitions_sasl_mechanisms.h
/usr/include/azure_uamqp_c/amqp_definitions_sasl_outcome.h
/usr/include/azure_uamqp_c/amqp_definitions_sasl_response.h
/usr/include/azure_uamqp_c/amqp_definitions_seconds.h
/usr/include/azure_uamqp_c/amqp_definitions_sender_settle_mode.h
/usr/include/azure_uamqp_c/amqp_definitions_sequence_no.h
/usr/include/azure_uamqp_c/amqp_definitions_session_error.h
/usr/include/azure_uamqp_c/amqp_definitions_source.h
/usr/include/azure_uamqp_c/amqp_definitions_target.h
/usr/include/azure_uamqp_c/amqp_definitions_terminus_durability.h
/usr/include/azure_uamqp_c/amqp_definitions_terminus_expiry_policy.h
/usr/include/azure_uamqp_c/amqp_definitions_transfer.h
/usr/include/azure_uamqp_c/amqp_definitions_transfer_number.h
/usr/include/azure_uamqp_c/amqp_frame_codec.h
/usr/include/azure_uamqp_c/amqp_management.h
/usr/include/azure_uamqp_c/amqp_types.h
/usr/include/azure_uamqp_c/amqpvalue.h
/usr/include/azure_uamqp_c/amqpvalue_to_string.h
/usr/include/azure_uamqp_c/async_operation.h
/usr/include/azure_uamqp_c/cbs.h
/usr/include/azure_uamqp_c/connection.h
/usr/include/azure_uamqp_c/frame_codec.h
/usr/include/azure_uamqp_c/header_detect_io.h
/usr/include/azure_uamqp_c/link.h
/usr/include/azure_uamqp_c/message.h
/usr/include/azure_uamqp_c/message_receiver.h
/usr/include/azure_uamqp_c/message_sender.h
/usr/include/azure_uamqp_c/messaging.h
/usr/include/azure_uamqp_c/sasl_anonymous.h
/usr/include/azure_uamqp_c/sasl_frame_codec.h
/usr/include/azure_uamqp_c/sasl_mechanism.h
/usr/include/azure_uamqp_c/sasl_mssbcbs.h
/usr/include/azure_uamqp_c/sasl_plain.h
/usr/include/azure_uamqp_c/sasl_server_io.h
/usr/include/azure_uamqp_c/sasl_server_mechanism.h
/usr/include/azure_uamqp_c/saslclientio.h
/usr/include/azure_uamqp_c/server_protocol_io.h
/usr/include/azure_uamqp_c/session.h
/usr/include/azure_uamqp_c/socket_listener.h
/usr/include/azure_uamqp_c/uamqp.h
/usr/include/azure_uhttp_c/uhttp.h
/usr/include/azure_umqtt_c/mqtt_client.h
/usr/include/azure_umqtt_c/mqtt_codec.h
/usr/include/azure_umqtt_c/mqtt_message.h
/usr/include/azure_umqtt_c/mqttconst.h
/usr/include/azureiot/agenttypesystem.h
/usr/include/azureiot/blob.h
/usr/include/azureiot/codefirst.h
/usr/include/azureiot/commanddecoder.h
/usr/include/azureiot/datamarshaller.h
/usr/include/azureiot/datapublisher.h
/usr/include/azureiot/dataserializer.h
/usr/include/azureiot/iotdevice.h
/usr/include/azureiot/iothub.h
/usr/include/azureiot/iothub_client.h
/usr/include/azureiot/iothub_client_authorization.h
/usr/include/azureiot/iothub_client_core.h
/usr/include/azureiot/iothub_client_core_common.h
/usr/include/azureiot/iothub_client_core_ll.h
/usr/include/azureiot/iothub_client_diagnostic.h
/usr/include/azureiot/iothub_client_edge.h
/usr/include/azureiot/iothub_client_hsm_ll.h
/usr/include/azureiot/iothub_client_ll.h
/usr/include/azureiot/iothub_client_ll_uploadtoblob.h
/usr/include/azureiot/iothub_client_options.h
/usr/include/azureiot/iothub_client_private.h
/usr/include/azureiot/iothub_client_retry_control.h
/usr/include/azureiot/iothub_client_version.h
/usr/include/azureiot/iothub_device_client.h
/usr/include/azureiot/iothub_device_client_ll.h
/usr/include/azureiot/iothub_message.h
/usr/include/azureiot/iothub_module_client.h
/usr/include/azureiot/iothub_module_client_ll.h
/usr/include/azureiot/iothub_transport_ll.h
/usr/include/azureiot/iothubtransport.h
/usr/include/azureiot/iothubtransport_amqp_cbs_auth.h
/usr/include/azureiot/iothubtransport_amqp_common.h
/usr/include/azureiot/iothubtransport_amqp_connection.h
/usr/include/azureiot/iothubtransport_amqp_device.h
/usr/include/azureiot/iothubtransport_amqp_messenger.h
/usr/include/azureiot/iothubtransport_amqp_telemetry_messenger.h
/usr/include/azureiot/iothubtransport_amqp_twin_messenger.h
/usr/include/azureiot/iothubtransport_mqtt_common.h
/usr/include/azureiot/iothubtransportamqp.h
/usr/include/azureiot/iothubtransportamqp_methods.h
/usr/include/azureiot/iothubtransportamqp_websockets.h
/usr/include/azureiot/iothubtransporthttp.h
/usr/include/azureiot/iothubtransportmqtt.h
/usr/include/azureiot/iothubtransportmqtt_websockets.h
/usr/include/azureiot/jsondecoder.h
/usr/include/azureiot/jsonencoder.h
/usr/include/azureiot/message_queue.h
/usr/include/azureiot/methodreturn.h
/usr/include/azureiot/multitree.h
/usr/include/azureiot/parson.h
/usr/include/azureiot/schema.h
/usr/include/azureiot/schemalib.h
/usr/include/azureiot/schemaserializer.h
/usr/include/azureiot/serializer.h
/usr/include/azureiot/serializer_devicetwin.h
/usr/include/azureiot/uamqp_messaging.h
/usr/include/iothub_service_client/iothub_deviceconfiguration.h
/usr/include/iothub_service_client/iothub_devicemethod.h
/usr/include/iothub_service_client/iothub_devicetwin.h
/usr/include/iothub_service_client/iothub_message.h
/usr/include/iothub_service_client/iothub_messaging.h
/usr/include/iothub_service_client/iothub_messaging_ll.h
/usr/include/iothub_service_client/iothub_registrymanager.h
/usr/include/iothub_service_client/iothub_sc_version.h
/usr/include/iothub_service_client/iothub_service_client_auth.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/iothub_client.so
/usr/lib64/iothub_service_client.so
/usr/lib64/libaziotsharedutil.so
/usr/lib64/libhsm_security_client.so
/usr/lib64/libiothub_client.so
/usr/lib64/libiothub_client.so.1
/usr/lib64/libiothub_client.so.1.2.9
/usr/lib64/libiothub_client_amqp_transport.so
/usr/lib64/libiothub_client_amqp_ws_transport.so
/usr/lib64/libiothub_client_http_transport.so
/usr/lib64/libiothub_client_mqtt_transport.so
/usr/lib64/libiothub_client_mqtt_ws_transport.so
/usr/lib64/libiothub_service_client.so
/usr/lib64/libiothub_service_client.so.1
/usr/lib64/libiothub_service_client.so.1.2.9
/usr/lib64/libmsr_riot.so
/usr/lib64/libparson.so
/usr/lib64/libprov_amqp_transport.so
/usr/lib64/libprov_amqp_ws_transport.so
/usr/lib64/libprov_auth_client.so
/usr/lib64/libprov_device_client.so
/usr/lib64/libprov_device_client.so.1
/usr/lib64/libprov_device_client.so.1.2.9
/usr/lib64/libprov_device_ll_client.so
/usr/lib64/libprov_http_transport.so
/usr/lib64/libprov_mqtt_transport.so
/usr/lib64/libprov_mqtt_ws_transport.so
/usr/lib64/libserializer.so
/usr/lib64/libserializer.so.1
/usr/lib64/libserializer.so.1.2.9
/usr/lib64/libuamqp.so
/usr/lib64/libuhttp.so
/usr/lib64/libumqtt.so
/usr/lib64/libumqtt.so.1
/usr/lib64/libumqtt.so.1.1.10
/usr/lib64/libutpm.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/azure-iot-sdk/03e1fe6fd0bc6d73c3cd3370d5f0a73c4fcb60d6
/usr/share/package-licenses/azure-iot-sdk/31034815375ad687af0a1b5d1c039587d3e93759
/usr/share/package-licenses/azure-iot-sdk/47e4690f60befa1918e5ac38723973fe4cf04e9b
/usr/share/package-licenses/azure-iot-sdk/6139d90e341cffe78b5b3f5a0f6c1becb6b6a4c7
/usr/share/package-licenses/azure-iot-sdk/6298ab377445ac77e0146fe1794ff402f52b5631
/usr/share/package-licenses/azure-iot-sdk/907314f1b5ac6f68c1906863389e4f2bed2a284d
/usr/share/package-licenses/azure-iot-sdk/b936129838be63462c2583bfd059d8736f39ab87
/usr/share/package-licenses/azure-iot-sdk/fc3defdb0ec07babc6fa8696113812c5a4ccd74a
/usr/share/package-licenses/azure-iot-sdk/fcd11f2e53968b872b48efbb6cf2a18c5a0d04e5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
